# Generated by Django 5.1.3 on 2024-12-06 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
                ('price', models.FloatField()),
                ('value', models.IntegerField()),
            ],
        ),
    ]
