# Generated by Django 5.1.3 on 2024-12-12 16:00

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='image',
            field=models.ImageField(default='profile.png', upload_to=apps.catalog.models.path_to_img),
        ),
    ]
