# Generated by Django 5.1.3 on 2024-12-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
