# Generated by Django 5.1.3 on 2024-12-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_good_has_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='income',
            field=models.FloatField(default=0.0),
        ),
    ]
