# Generated by Django 5.1.3 on 2024-12-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_good_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='destination',
        ),
    ]
