# Generated by Django 5.1.3 on 2024-12-17 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0005_alter_good_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitsPerWeek',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('date_crated', models.DateTimeField(default=datetime.datetime.today)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
