# Generated by Django 5.1.3 on 2024-12-17 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0006_visitsperweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitsperweek',
            name='good',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='catalog.good',
            ),
            preserve_default=False,
        ),
    ]
