# Generated by Django 5.1.3 on 2024-12-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
